ip_forward: true
network_compression_threshold: 256
stats: d72ae4c2-a2de-44d9-abfc-ad4178603d65
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - skinsrestorer.playercmds
  - bungeecord.command.skin
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  dothe:
  - admin
servers:
  Hub:
    motd: '&6&k@@&a &LMINELG.COM &6&k@@&4  &L<<=>>  &b&LMINE OF THE BEST   &5&L[&7&L1.10-1.11&5&L]         &6&L>>   &9&LTOWNY   &3&L-   &7&LPRISON   &4&L-   &e&LSKYBLOCK   &6&L<<'
    address: 192.168.69.196:25596
    restricted: false
  Towny:
    motd: '&6&k@@&a &LMINELG.COM &6&k@@&4  &L<<=>>  &b&LMINE OF THE BEST   &5&L[&7&L1.10-1.11&5&L]         &6&L>>   &9&LTOWNY   &3&L-   &7&LPRISON   &4&L-   &e&LSKYBLOCK   &6&L<<'
    address: 192.168.69.196:25597
    restricted: false
  Prison:
    motd: '&6&k@@&a &LMINELG.COM &6&k@@&4  &L<<=>>  &b&LMINE OF THE BEST   &5&L[&7&L1.10-1.11&5&L]         &6&L>>   &9&LTOWNY   &3&L-   &7&LPRISON   &4&L-   &e&LSKYBLOCK   &6&L<<'
    address: 192.168.69.196:25598
    restricted: false
  Skyblock:
    motd: '&6&k@@&a &LMINELG.COM &6&k@@&4  &L<<=>>  &b&LMINE OF THE BEST   &5&L[&7&L1.10-1.11&5&L]         &6&L>>   &9&LTOWNY   &3&L-   &7&LPRISON   &4&L-   &e&LSKYBLOCK   &6&L<<'
    address: 192.168.69.196:25599
    restricted: false
timeout: 30000
listeners:
- query_port: 25565
  motd: '&6&k@@&a &LMINELG.COM &6&k@@&4  &L<<=>>  &b&LMINE OF THE BEST   &5&L[&7&L1.10-1.11&5&L]         &6&L>>   &9&LTOWNY   &3&L-   &7&LPRISON   &4&L-   &e&LSKYBLOCK   &6&L<<'
  priorities:
  - Hub
  bind_local_address: false
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 192.168.69.196:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 600
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
